<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <IsPackable>false</IsPackable>
    <Configurations>Debug;Release</Configurations>
    <NeutralLanguage>en-US</NeutralLanguage>
    <RollForward>Major</RollForward>

    <AssemblyName>RJCP.IO.Ports.ComTest</AssemblyName>
    <AssemblyTitle>RJCP.IO.Ports.ComTest</AssemblyTitle>
    <Product>RJCP.SerialPortStreamt</Product>
    <RootNamespace>RJCP.IO.Ports.ComTest</RootNamespace>

    <Authors>Jason Curl</Authors>
    <Copyright>(C) 2026, Jason Curl</Copyright>
    <Company></Company>
    <Description>Description of the app.</Description>
    <Version>1.0.0</Version>

    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>Default</AnalysisMode>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnableDefaultItems>false</EnableDefaultItems>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <LangVersion Condition="$(TargetFramework.StartsWith('net4'))">10</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <PackageReference Include="System.Resources.Extensions" version="4.6.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CSharpIsNullAnalyzer" Version="0.1.593" PrivateAssets="all" />
    <ProjectReference Include="..\..\..\..\code\SerialPortStream.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Form1.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Form1.Designer.cs">
      <DependentUpon>Form1.cs</DependentUpon>
    </Compile>
    <Compile Include="Program.cs" />
    <EmbeddedResource Include="Form1.resx">
      <DependentUpon>Form1.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
</Project>