<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <IsPackable>false</IsPackable>

    <AssemblyName>SerialPortStream.AotSmoke</AssemblyName>
    <RootNamespace>RJCP.IO.Ports</RootNamespace>

    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>Default</AnalysisMode>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\code\SerialPortStream.csproj" />
  </ItemGroup>
</Project>
